@startuml

package core {
    package pachy {
        class FCCore {
            - telem: DataSink*
            - flash: FlashDevice*
            - config: ConfigSource*
            - file: StorageSink*
            - log: FlashSink
            + FCCore(telem_sink: DataSink*, flash_dev: FlashDevice*, config: ConfigSource*, fs: StorageSink*)
            + begin(): void
            + step(): void
        }
        FCCore --> DataSink
        FCCore --> FlashDevice
        FCCore --> FlashSink
        FCCore --> ConfigSource

        interface DataSink {
            + buf_avail(): size_t
            + write(data: const char*, size: size_t): void
        }

        interface FlashDevice {
            + {static} ERASE_SIZE: constexpr size_t 
            + {static} FLASH_SIZE: constexpr size_t
            + read(addr: size_t, buffer: char*, size: size_t): bool
            + write(addr: size_t, data: const char*, size: size_t): bool
            + erase(addr: size_t): bool
        }

        interface ConfigSource {
            + open(filename: const char*): bool
            + read(section: const char*, header: const char*): bool
        }

        interface StorageSink {
            + open(filename: const char*): bool
            + close(): bool
        }
        StorageSink ..|> DataSink

        class FlashSink {
            - flash: FlashDevice*
            + FlashSink(flash_dev: FlashDevice*)
            + init(): size_t
            + buf_avail(): size_t
            + write(data: const char*, size: size_t): void
        }
        FlashSink --> FlashDevice
        FlashSink .r.|> DataSink
    }
}

package inipp {
    class Ini {
    } 
}

package sil {
    class StreamSink {
        + buf_avail(): size_t
        + write(data: const char*, size: size_t): void
    }
    StreamSink .u.|> core.pachy.DataSink

    class FlashImage {
        + read(addr: size_t, buffer, char*, size: size_t): bool
        + write(addr: size_t, data: const char*, size: size_t): bool
        + erase_64k(addr: size_t): bool
    }
    FlashImage .u.|> core.pachy.FlashDevice

    class FileConfig {
        - source: Ini
        - dir: string
        + FileConfig(rootdir: string)
        + open(filename: const char*): bool
        + read(section: const char*, header: const char*): bool
        
    }
    FileConfig .u.|> core.pachy.ConfigSource
    FileConfig --> inipp.Ini

    class FileStorage {
        - dir: string
        - file: ofstream
        + FileStorage(rootdir: string)
        + open(path: const char*): bool
        + close(): bool
        + buf_avail(): size_t
        + write(data: const char*, size: size_t): void
    }
    FileStorage .u.|> core.pachy.StorageSink
}

package firmware {
    class main {
        - core: FCCore
        - telem_sink: RFSink
        - flash_dev: WinbondFlash
    }
    main --> core.pachy.FCCore
    main --> RFSink
    main --> WinbondFlash

    class RFSink {
        + RFSink(...)
    }
    RFSink .u.|> core.pachy.DataSink

    class WinbondFlash {
        + WinbondFlash(...)
    }
    WinbondFlash .u.|> core.pachy.FlashDevice
}
@enduml